"use client";

import Link from "next/link";
import {
  FileText,
  GraduationCap,
  Minus,
  PlusCircle,
  Settings,
  HelpCircle,
  BookOpen,
} from "lucide-react";
import type { ReactNode } from "react";
import type {
  ClarificationPrompt,
  SummaryResult,
  ExplanationResult,
  AssignmentResult,
  RevisionResult,
  SolveResult,
  StudyMode,
} from "@/types";

interface ResultsViewProps {
  sourceText: string;
  summaryData: SummaryResult | null;
  explainData: ExplanationResult | null;
  assignmentData: AssignmentResult | null;
  revisionData: RevisionResult | null;
  solveData?: SolveResult | null;
  activeMode: StudyMode;
  isGenerating: boolean;
  error?: string;
  clarification: ClarificationPrompt | null;
  onClarificationSelect: (option: string) => void;
  onNewSession: () => void;
}

export function ResultsView({
  sourceText,
  summaryData,
  explainData,
  assignmentData,
  revisionData,
  solveData,
  activeMode,
  isGenerating,
  error,
  clarification,
  onClarificationSelect,
  onNewSession,
}: ResultsViewProps) {
  const structuredData = summaryData ?? explainData ?? assignmentData;
  const title = structuredData?.title || deriveTitle(sourceText);
  const subtitle =
    structuredData?.introduction ||
    "An editorial deep-dive generated by Saar AI based on your study material.";
  const coreConcepts = structuredData?.coreConcepts ?? [];
  const sections = structuredData?.sections ?? [];
  const relatedTopics = structuredData?.relatedTopics ?? [];

  /* Derive a subject breadcrumb from the title */
  const breadcrumb = deriveBreadcrumb(title);

  return (
    <div className="flex min-h-screen w-full bg-white font-sans text-ink">
      {/* ─── SIDEBAR ─── */}
      <aside className="sticky top-0 flex h-screen w-[240px] shrink-0 flex-col border-r border-slate-100 bg-[#f8fafc]">
        {/* Brand */}
        <div className="px-6 pt-5 pb-2">
          <Link href="/" className="text-lg font-bold tracking-tight text-primary">
            Saar AI
          </Link>
          <div className="mt-3 flex items-center gap-1 text-[10px] font-semibold uppercase tracking-[0.1em] text-slate-400">
            <span>{breadcrumb}</span>
          </div>
        </div>

        {/* New Session */}
        <div className="px-4 pt-3 pb-4">
          <button
            type="button"
            onClick={onNewSession}
            className="flex w-full items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-[13px] font-semibold text-white shadow-md shadow-primary/20 transition hover:bg-blue-700"
          >
            <PlusCircle className="h-4 w-4" />
            New Session
          </button>
        </div>

        {/* Navigation */}
        <nav className="flex flex-1 flex-col px-3">
          <a
            href="#summary"
            className="flex items-center gap-3 rounded-lg bg-white px-3 py-2.5 text-[13px] font-semibold text-primary shadow-sm"
          >
            <Minus className="h-3.5 w-3.5" />
            Summary
          </a>
          <a
            href="#framework"
            className="mt-1 flex items-center gap-3 rounded-lg px-3 py-2.5 text-[13px] font-medium text-slate-500 transition hover:bg-white"
          >
            <GraduationCap className="h-3.5 w-3.5" />
            Explain
          </a>
          <a
            href="#assessments"
            className="mt-1 flex items-center gap-3 rounded-lg px-3 py-2.5 text-[13px] font-medium text-slate-500 transition hover:bg-white"
          >
            <FileText className="h-3.5 w-3.5" />
            Assignment
          </a>

          <div className="my-4 h-px bg-slate-200/80" />

          <a
            href="#"
            className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-[13px] font-medium text-slate-400 transition hover:bg-white hover:text-slate-600"
          >
            <Settings className="h-3.5 w-3.5" />
            Settings
          </a>
          <a
            href="#"
            className="mt-1 flex items-center gap-3 rounded-lg px-3 py-2.5 text-[13px] font-medium text-slate-400 transition hover:bg-white hover:text-slate-600"
          >
            <HelpCircle className="h-3.5 w-3.5" />
            Support
          </a>
        </nav>
      </aside>

      {/* ─── MAIN CONTENT ─── */}
      <main className="flex-1 overflow-y-auto">
        {/* Top bar */}
        <div className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-100 bg-white/80 px-8 py-3 backdrop-blur-md">
          <nav className="flex items-center gap-6 text-[13px] font-medium">
            <a
              href="/dashboard"
              className="text-primary underline underline-offset-4 decoration-2"
            >
              Dashboard
            </a>
            <a href="#" className="text-slate-400 hover:text-slate-700">
              History
            </a>
            <a href="#" className="text-slate-400 hover:text-slate-700">
              Library
            </a>
          </nav>
          <div className="flex items-center gap-3">
            <button
              type="button"
              className="rounded-full p-2 text-slate-400 transition hover:bg-slate-100"
            >
              <Settings className="h-4 w-4" />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="mx-auto max-w-5xl px-8 py-10 lg:px-12">
          {/* Breadcrumb */}
          <div className="mb-4 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.1em] text-primary">
            <BookOpen className="h-3.5 w-3.5" />
            <span>{breadcrumb}</span>
          </div>

          {/* Title */}
          <h1 className="text-[34px] font-bold leading-tight tracking-tight text-slate-900 sm:text-[40px]">
            {title}
          </h1>
          <p className="mt-4 max-w-3xl text-[15px] leading-7 text-slate-500">
            {subtitle}
          </p>

          {error ? (
            <div className="mt-8 rounded-xl border border-red-100 bg-red-50 px-5 py-4 text-sm text-red-700">
              {error}
            </div>
          ) : null}

          {clarification ? (
            <section className="mt-8 rounded-2xl border border-amber-200 bg-amber-50/70 p-6">
              <p className="text-sm font-semibold text-slate-900">{clarification.message}</p>
              <div className="mt-4 flex flex-wrap gap-3">
                {clarification.options.map((option) => (
                  <button
                    key={option}
                    type="button"
                    onClick={() => onClarificationSelect(option)}
                    className="rounded-full border border-amber-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 transition hover:border-primary hover:text-primary"
                  >
                    {option}
                  </button>
                ))}
              </div>
            </section>
          ) : null}

          {isGenerating ? (
            <section className="mt-12 rounded-2xl border border-slate-200 bg-[#f8fafc] p-8">
              <div className="flex items-center gap-4">
                <div className="h-10 w-10 animate-spin rounded-full border-4 border-primary/20 border-t-primary" />
                <div>
                  <p className="text-sm font-semibold text-slate-800">Generating your {activeMode}...</p>
                  <p className="text-sm text-slate-500">
                    Saar AI is analyzing the material and building the output now.
                  </p>
                </div>
              </div>
            </section>
          ) : null}

          {structuredData ? (
            <>
              {coreConcepts.length > 0 ? (
                <section id="summary" className="mt-12">
                  <div className="rounded-2xl border border-slate-200 bg-[#f8fafc] p-6 sm:p-7">
                    <div className="flex items-center gap-3">
                      <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-600 text-white">
                        <Minus className="h-4 w-4" />
                      </div>
                      <div>
                        <h2 className="text-[20px] font-bold tracking-tight text-slate-900">
                          Core Concepts
                        </h2>
                        <p className="text-sm text-slate-500">Revision-ready highlights in one glance.</p>
                      </div>
                    </div>
                    <ul className="mt-5 space-y-3">
                      {coreConcepts.map((point, i) => (
                        <li key={i} className="flex gap-3 text-[14px] leading-6 text-slate-700">
                          <span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-primary" />
                          <span>{highlightKeyTerms(point)}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </section>
              ) : null}

              {sections.length > 0 ? (
                <section id="framework" className="mt-14 space-y-8">
                  {sections.map((section) => (
                    <article
                      key={section.heading}
                      id={toAnchorId(section.heading)}
                      className="rounded-2xl border border-slate-200 bg-white p-6 sm:p-7"
                    >
                      <h2 className="text-[24px] font-bold tracking-tight text-slate-900">
                        {section.heading}
                      </h2>

                      {section.paragraph ? (
                        <p className="mt-4 max-w-4xl text-[15px] leading-7 text-slate-600">
                          {section.paragraph}
                        </p>
                      ) : null}

                      {section.points.length > 0 ? (
                        <ul className="mt-5 space-y-3">
                          {section.points.map((point, i) => (
                            <li key={i} className="flex gap-3 text-[14px] leading-6 text-slate-700">
                              <span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-primary" />
                              <span>{highlightKeyTerms(point)}</span>
                            </li>
                          ))}
                        </ul>
                      ) : null}

                      {section.subsections.length > 0 ? (
                        <div className="mt-6 grid gap-4 md:grid-cols-2">
                          {section.subsections.map((subsection) => (
                            <div key={subsection.heading} className="rounded-xl border border-slate-200 bg-[#f8fafc] p-5">
                              <h3 className="text-[16px] font-semibold text-slate-900">
                                {subsection.heading}
                              </h3>
                              <ul className="mt-3 space-y-2">
                                {subsection.points.map((point, i) => (
                                  <li key={i} className="flex gap-2 text-[13px] leading-6 text-slate-600">
                                    <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />
                                    <span>{highlightKeyTerms(point)}</span>
                                  </li>
                                ))}
                              </ul>
                            </div>
                          ))}
                        </div>
                      ) : null}
                    </article>
                  ))}
                </section>
              ) : null}
            </>
          ) : null}

          {/* ── CRITICAL ASSESSMENTS ── */}
          {assignmentData && (
            <section id="assessments" className="mt-16">
              <div className="mb-6 flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-50">
                    <FileText className="h-4 w-4 text-primary" />
                  </div>
                  <h2 className="text-[20px] font-bold tracking-tight text-slate-900">
                    Critical Assessments
                  </h2>
                </div>
                <div className="flex gap-2">
                  <span className="rounded-full bg-slate-100 px-3 py-1 text-[11px] font-semibold text-slate-500">
                    Quick Assessment
                  </span>
                  <span className="rounded-full bg-blue-50 px-3 py-1 text-[11px] font-semibold text-primary">
                    Long Answer
                  </span>
                </div>
              </div>

              {assignmentData.instructions && (
                <p className="mb-6 max-w-4xl text-[14px] leading-6 text-slate-500">
                  {assignmentData.instructions}
                </p>
              )}

              <div className="grid gap-5 md:grid-cols-2">
                {assignmentData.questions.map((q, i) => (
                  <div
                    key={i}
                    className="rounded-xl border border-slate-200 bg-[#f8fafc] p-6 transition-shadow hover:shadow-md"
                  >
                    <p className="mb-3 text-[11px] font-bold uppercase tracking-[0.12em] text-primary">
                      Question #{i + 1}
                    </p>
                    <p className="text-[15px] font-semibold leading-6 text-slate-800">
                      {q.question}
                    </p>
                    <div className="mt-4 rounded-lg bg-white p-4 text-[13px] leading-6 text-slate-600 shadow-sm">
                      {q.answer}
                    </div>
                  </div>
                ))}
              </div>
            </section>
          )}

          {/* ── REVISION MODE ── */}
          {revisionData && (
            <section id="revision" className="mt-16">
              <div className="mb-6 flex items-center gap-3">
                <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-50">
                  <BookOpen className="h-4 w-4 text-primary" />
                </div>
                <h2 className="text-[20px] font-bold tracking-tight text-slate-900">
                  Revision Mode
                </h2>
              </div>
              
              <div className="grid gap-6 md:grid-cols-2">
                <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
                  <h3 className="mb-4 text-[13px] font-bold uppercase tracking-[0.1em] text-slate-800">
                    Key Concepts
                  </h3>
                  <ul className="space-y-2">
                    {revisionData.keyConcepts.map((item, i) => (
                      <li key={i} className="flex gap-2 text-[14px] leading-6 text-slate-600">
                        <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />
                        <span>{item.term}: {item.definition}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
                  <h3 className="mb-4 text-[13px] font-bold uppercase tracking-[0.1em] text-slate-800">
                    Quick Recall
                  </h3>
                  <div className="space-y-4">
                    {revisionData.shortQuestions.map((item, i) => (
                      <div key={i}>
                        <p className="text-[14px] font-bold text-slate-800">{item.question}</p>
                        <p className="text-[14px] leading-6 text-slate-500">{item.answer}</p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </section>
          )}

          {solveData && (
            <section id="solve" className="mt-16">
              <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
                <h2 className="text-[20px] font-bold tracking-tight text-slate-900">Solve Mode</h2>
                <p className="mt-3 text-[14px] leading-6 text-slate-500">
                  {solveData.frameworkLabel} for a {solveData.topicType} question.
                </p>
              </div>
            </section>
          )}

          {relatedTopics.length > 0 ? (
            <section className="mt-16">
              <div className="rounded-2xl border border-blue-100 bg-blue-50/30 p-6">
                <h2 className="text-[20px] font-bold tracking-tight text-slate-900">
                  Explore Related Topics
                </h2>
                <p className="mt-2 text-sm text-slate-500">
                  Continue with a deeper or adjacent concept in one click.
                </p>
                <div className="mt-5 flex flex-wrap gap-3">
                  {relatedTopics.map((topic) => (
                    <button
                      key={topic}
                      type="button"
                      onClick={() => onClarificationSelect(topic)}
                      className="rounded-full border border-blue-200 bg-white px-4 py-2 text-sm font-medium text-slate-700 transition hover:border-primary hover:text-primary"
                    >
                      {topic}
                    </button>
                  ))}
                </div>
              </div>
            </section>
          ) : null}
        </div>

        {/* Footer */}
        <footer className="border-t border-slate-100 bg-white">
          <div className="mx-auto flex max-w-5xl flex-col items-center justify-between gap-4 px-8 py-5 sm:flex-row lg:px-12">
            <p className="text-[11px] font-semibold uppercase tracking-[0.06em] text-slate-300">
              © 2024 Saar AI Editorial. Soft-minimal ISM.
            </p>
            <div className="flex gap-6 text-[11px] font-semibold uppercase tracking-[0.06em] text-slate-300">
              <span className="cursor-pointer transition hover:text-slate-500">
                Privacy
              </span>
              <span className="cursor-pointer transition hover:text-slate-500">
                Terms
              </span>
              <span className="cursor-pointer transition hover:text-slate-500">
                Methodology
              </span>
            </div>
          </div>
        </footer>
      </main>
    </div>
  );
}

/* ── Helpers ── */

function deriveTitle(sourceText: string): string {
  const firstLine = sourceText.trim().split("\n")[0] || "";
  if (firstLine.length > 5 && firstLine.length < 80) {
    return firstLine.replace(/^#+\s*/, "");
  }
  const words = sourceText.trim().split(/\s+/).slice(0, 6).join(" ");
  return words.length > 3 ? words + "..." : "Study Analysis";
}

function deriveBreadcrumb(title: string): string {
  const words = title.split(/\s+/).slice(0, 3).join(" ").toUpperCase();
  return words || "STUDY MATERIAL";
}

function toAnchorId(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function highlightKeyTerms(text: string): ReactNode {
  const parts = text.split(/(\*\*[^*]+\*\*)/g);

  return parts.map((part, index) => {
    if (part.startsWith("**") && part.endsWith("**")) {
      return <strong key={`${part}-${index}`} className="font-semibold text-slate-900">{part.slice(2, -2)}</strong>;
    }

    return <span key={`${part}-${index}`}>{part}</span>;
  });
}
